### ISSUE TITLE
User Registration Error

### ISSUE THREAD

**Issue by tolu-c** [divanov11/proshop_django#1]
![signUp -401 error](https://user-images.githubusercontent.com/68569546/112337002-d5497200-8cbd-11eb-9a13-13002ec3c2f1.PNG)

![postman- error 401](https://user-images.githubusercontent.com/68569546/112337167-f90cb800-8cbd-11eb-862a-e0632f50c45e.PNG)

I Get an error saying `Authentication credentials were not provided.` 
when I try to register a new user.
And my code is literally the same. This i the fifth time I am trying this.

from the console : `POST http://localhost:3000/api/users/register/ 401 (Unauthorized)`
from the redux state: 
```
loading(pin):false
error(pin):"Authentication credentials were not provided."
```

it also doesn't work on postman

**Comment by msebak** [comment]
how have you solved it ?
