### ISSUE TITLE
Having Trouble With React Router DOM

### ISSUE THREAD

**Issue by bhavdeep-saragadam** [divanov11/proshop_django#27]
It shows a blank screen 
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/58917780/180306615-5a519d68-0dc5-4fa5-82b0-581c5b09d602.png">

**Comment by Gallahad072** [comment]
I believe you've entered 'pathname' where you should have entered the pathname of the directory you need to refer to.

**Comment by mushfiqur-rahman** [comment]
Well I am facing same issue  and solve it. 
Though I am using 
`react-router-dom@6`

So I had to modify `app.js`  and `index.js`  like below

**Index.js**


![image](https://user-images.githubusercontent.com/26889268/185016199-ca97f126-0339-44c5-bdf1-7bbf6b483c8f.png)


and **app.js**

![image](https://user-images.githubusercontent.com/26889268/185016337-7abab6ae-abc7-409b-bde0-b4788e30979e.png)


Hope this will work for anyone if they are using `react-router-dom@6`
